[versions]
# project modules version
p-root = "2.1.1-dev"
p-qqrobot-framework-api = "2.0.2-dev"
p-qqrobot-spring-boot-starter = "2.0.2-dev"
p-file-receiver = "1.0.2-dev"

# gradle plugins version
gp-honoka-basic = "1.1.0-dev"

# dependencies version
d-kotlin = "2.2.21"
d-kotlin-coroutines = "1.10.2"
d-lombok = "1.18.42"
d-spring-boot = "3.5.9"
d-honoka-spring-boot-starter = "1.1.0-dev"
d-qqrobot-framework-api = "2.0.2-dev"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "d-kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "d-kotlin" }
kotlin-lombok = { id = "org.jetbrains.kotlin.plugin.lombok", version.ref = "d-kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "d-kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "d-spring-boot" }
honoka-basic = { id = "de.honoka.gradle.plugin.basic", version.ref = "gp-honoka-basic" }

[libraries]
honoka-spring-boot-starter = { module = "de.honoka.sdk:honoka-spring-boot-starter", version.ref = "d-honoka-spring-boot-starter" }
qqrobot-framework-api = { module = "de.honoka.qqrobot:qqrobot-framework-api", version.ref = "d-qqrobot-framework-api" }
