[versions]
# project modules version
root = "1.3.3"
qqrobot-framework-api = "1.0.3"
qqrobot-spring-boot-starter = "1.3.3"

# dependencies version
spring-boot = "2.7.5"
mirai = "2.14.0"
kotlin = "1.8.10"
kotlin-coroutines = "1.6.3"
lombok = "1.18.26"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dependency-management = "io.spring.dependency-management:1.0.11.RELEASE"

[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
mirai-core = { module = "net.mamoe:mirai-core-jvm", version.ref = "mirai" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }