name: Gradle CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - id: gradle_build
        name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew -PremoteMavenRepositoryUrl=$(pwd)/build/temp-maven-repo publish
          echo "project_version=$(./gradlew properties | grep 'version:\s')" >> "$GITHUB_OUTPUT"
      - name: Upload temporary maven repository
        uses: actions/upload-artifact@v3
        with:
          name: temp-maven-repo
          path: build/temp-maven-repo
    outputs:
      project_version: ${{ steps.gradle_build.outputs.project_version }}
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check project version
        env:
          project_version: ${{ needs.build.outputs.project_version }}
        run: |
          echo "\$project_version: \"$project_version\""
          if [ "$(echo $project_version | grep -i dev)" != '' ]; then
            echo 'Cannot publish development versions!'
            exit 10
          fi
      - name: Download temporary maven repository
        uses: actions/download-artifact@v3
        with:
          name: temp-maven-repo
          path: build/temp-maven-repo
      - name: Clone remote maven repository
        run: |
          git clone ${{ secrets.REMOTE_MAVEN_REPO_URL }}
      - name: Merge maven repository and publish
        run: |
          cp -rf build/temp-maven-repo/* maven-repo/repository/
          cd maven-repo/repository
          git config --global user.name 'Kosaka Bun'
          git config --global user.email 'kosaka-bun@qq.com'
          git add .
          git commit -m 'Update qqrobot-sdk'
          git push